#!/usr/bin/python3
import sys
import time
"""Factorize as many numbers as possible into a product of two smaller numbers"""
def factorize(nbr):
    """Number as input
    Args:
        nbr: input integer
        Return: 
    """
    for i in range(2, int(nbr**0.5)+1):
        if nbr % i == 0:
            return (i, nbr//i)
    return None

if __name__ == "__main__":
    """Reads the input file"""

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()
    input_file = sys.argv[1]
    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    start_time = time.time()
    """
    Iterates through each line, assuming that each line contains
    a single natural number. For each number, it invokes the 
    factorize function. If the function returns a tuple of factors,
    it displays the factorization in the specified format.
    """
    for line in lines:
        nbr = int(line.strip())
        factors = factorize(nbr)
        if factors:
            print(f"{nbr}={factors[1]}*{factors[0]}")

        """
        If running time exceeds 5 seconds,
        the program exits with an error message.
        """
        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
